---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}
data:
    {{- if not .Values.isGPGSealedSecret }}
    gpg-key: |
        {{- .Values.gpgKeyContent | nindent 8 }}
    {{- end }}
    {{- if index .Values "env" }}
    {{- with .Values.env }}
    {{- range $key, $value := . }}
    {{ $key }}: |
        {{- $value | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- end }}

{{- if .Values.isGPGSealedSecret }}
---
{{ .Values.gpgKeyContent }}
{{- end }}
