---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}
data:
    {{- if not .Values.isGPGSealedSecret }}
    gpg-key: "{{- .Values.gpgKeyContent | b64enc }}"
    {{- end }}
    {{- if index .Values "env" }}
    {{- with .Values.env }}
    {{- range $key, $value := . }}
    {{ $key }}: "{{ $value | b64enc }}"
    {{- end }}
    {{- end }}
    {{- end }}

{{- if .Values.isGPGSealedSecret }}
---
{{ .Values.gpgKeyContent }}
{{- end }}
