name: Release
on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: "make build_bm build_bmg"

            - name: Release binaries to GitHub releases
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      .build/backup-maker
                      .build/bmg
                      LICENSE

            - name: Build docker
              run: "make build_docker push_docker DOCKER_TAG=${GITHUB_REF##*/}"

            - name: Create Arch Linux package
              uses: 2m/arch-pkgbuild-builder@v1.18
              with:
                  target: 'pkgbuild'
                  pkgname: './'

            - name: Release Arch Linux package
              uses: softprops/action-gh-release@v1
              with:
                  files: "backup-maker-*.pkg.tar.zst"

