name: Release
on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Build
              run: "make build_bm build_bmg"

            - name: Release binaries to GitHub releases
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      .build/backup-maker
                      .build/bmg
                      LICENSE

            - name: Create Arch Linux package
              uses: 2m/arch-pkgbuild-builder@v1.18
              with:
                  target: 'pkgbuild'
                  pkgname: './'

            - name: Release Arch Linux package
              uses: softprops/action-gh-release@v1
              with:
                  files: "backup-maker-*.pkg.tar.zst"

            - uses: actions/upload-artifact@v2
              with:
                  name: binary
                  path: .build/b*

    release-docker:
        runs-on: ubuntu-latest
        needs: ["release"]
        strategy:
            max-parallel: 2
            matrix:
                include:
                    - POSTGRES_VERSION: "14.0"
                    - POSTGRES_VERSION: "13.0"
                    - POSTGRES_VERSION: "12.0"
                    - POSTGRES_VERSION: "11.0"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/download-artifact@v3
              with:
                  name: binary
                  path: .build/

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and release docker
              run: "make build_docker push_docker DOCKER_TAG=${GITHUB_REF##*/}-pg POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"
