name: Test
on:
    pull_request:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Install dependencies for testing
              run: "apt-get update && apt-get install -f mariadb-client"

            - name: Build
              run: "make build_bm build_bmg"

            - name: Test
              run: "make coverage"

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - uses: actions/upload-artifact@v2
              with:
                  name: binary
                  path: .build/b*

    check-packaging:
        runs-on: ubuntu-latest
        needs: ["test"]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/download-artifact@v2
              with:
                  name: binary
                  path: .build/

            - name: Create Arch Linux package
              uses: 2m/arch-pkgbuild-builder@v1.18
              with:
                  target: 'pkgbuild'
                  pkgname: './'

    release-snapshot-docker:
        runs-on: ubuntu-latest
        needs: ["test"]
        strategy:
            max-parallel: 2
            matrix:
                include:
                    - POSTGRES_VERSION: "14.0"
                    - POSTGRES_VERSION: "13.0"
                    - POSTGRES_VERSION: "12.0"
                    - POSTGRES_VERSION: "11.0"
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/download-artifact@v2
              with:
                  name: binary
                  path: .build/

            - name: Build and release docker
              run: "make build_docker push_docker DOCKER_TAG=snapshot-pg${{ matrix.POSTGRES_VERSION }} POSTGRES_VERSION=${{ matrix.POSTGRES_VERSION }}"
